config/routes.rb
Psyqic::Application.routes.draw do
  get  'auth/login'
  get  'auth/logout'
  post 'auth/login'
  match 'auth/:provider/callback', to: 'auth#callback'

  resources :predictions
  resources :options
  resources :users
  resources :questions
  resources :categories

  root :to => 'questions#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :user_id, :content, :correct_option_id
  attr_accessible :label_ids

  belongs_to :category
  belongs_to :user
  belongs_to :correct_option, :class_name => 'Option'
  has_and_belongs_to_many :labels

  has_many :options, :dependent => :destroy
  has_many :predictions, :through => :options

  validates :content, :presence => true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # before_filter :authorize_question_creator, :only => [:edit, :update, :destroy]
  helper_method :question_creator?

  def authorize_question_creator
    if ! question_creator?
      flash[:error] = 'The action is only allowed to the creator of the question.'
      redirect_to :back
    end
  end

  def question_creator?
    true
    # user = User.find(session[:user_id])
    # question = Question.find(params[:id])
    # user.id == question.user_id
  end


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    @question.user_id = session[:user_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="container">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h4>
        <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field row">
      <div class="col-sm-2 col-xs-12">
        <%= f.label :content, 'Question:' %>
      </div>
      <div class="col-sm-10 col-xs-12">
        <%= f.text_area :content, :rows => 5 %>
      </div>
      <br />
    </div>

      <div class="field row">
        <div class="col-sm-2 col-xs-12">
          <%= label_tag 'By:' %>
        </div>
        <div class="col-sm-10 col-xs-12">
          <%= @question.user.first_name + " " + @question.user.last_name %>
          <%= f.hidden_field :user_id %>
        </div>
      </div>
      <br />

      <div class="field row">
        <div class="col-sm-2 col-xs-12">
          <%= f.label :category_id, 'Category:' %>
        </div>
        <div class="col-sm-10 col-xs-12">
          <% all_categories = Category.all %>
          <% menu_items = all_categories.map { |c| [ c.name, c.id ] } %>
          <%= f.select :category_id, menu_items, :class => 'form-control' %>
        </div>
      </div>

      <div class="field row">
        <div class="col-sm-2 col-xs-12">
          <%= label_tag 'Labels:' %>
        </div>
        <div class="col-sm-10 col-xs-12">
          <% Label.all.each do | label | %>
              <%= check_box_tag 'question[label_ids][]', label.id, @question.labels.include?(label) %>
              <%= label.name %>
          <% end %>
        </div>
      </div>



      <br />

      <div class="field row">
        <div class="col-sm-2 col-xs-12">
        <%= f.label :correct_option_id, 'Correct Option:' %>
        </div>
        <div class="col-sm-10 col-xs-12">
        <% menu_items = [['Not decided', '']] + @question.options.map { |o| [ o.content, o.id ] } %>
        <%= f.select :correct_option_id, menu_items %>
        </div>
      </div>
      <br />

      <div class="actions row">
        <div class="col-sm-12 col-xs-12">
        <%= f.submit :class => 'btn btn-primary btn-sm' %>
        <%= link_to 'Cancel', :back, :class => 'btn btn-default btn-sm' %>
        </div>
      </div>
  <% end %>
  </div>

app/views/questions/edit.html.erb
<h3>Editing Question</h3>
<div class="container">
  <%= render 'form' %>
</div>

app/views/questions/index.html.erb
<div class="top-space">
</div>

<div class="container">
  <% @questions.each do |question| %>
<div class="row">
  <div class="col-sm-1 col-xs-3">
    <%= link_to(question.user) do %>
      <%= image_tag(question.user.image_url, :class => 'list-profile-image') if question.user.image? %>
    <% end %>
  </div>
  <div class="col-sm-9 col-xs-7">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <%= link_to(question.user, :class=> 'link-text') do %>
            <%= question.user.first_name + " " + question.user.last_name %> <br/>
        <% end %>
        <%= link_to(question, :class=> 'link-text') do %>
            <%= question.content %>
        <% end %>
        <br />
        <% question.labels.each do |label| %>
            <div class="category-label category-<%= question.category.name.downcase[0..2]%>">
              <%= label.name %>
            </div>
        <% end %>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="category-label category-<%= question.category.name.downcase[0..2]%>">
      <%= question.category.name %>
    </div>
      </div>
    </div>
  </div>
  <div class="col-sm-2 col-xs-2">
    <%= image_tag 'crystalball.png', :retina => true%>
    <span class="metadata-text">
      <%= question.predictions.count %>
    </span>
  </div>
</div>
<hr />
<% end %>
<%= link_to 'New Question', new_question_path, :class => 'btn btn-primary' %>
</div>
<br />

app/views/questions/new.html.erb
<h3>New Question</h3>
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="top-space">
</div>
<div class="container">

  <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
  <% end %>

  <div class="row">
  <div class="col-sm-1 col-xs-2">
    <%= link_to(@question.user) do %>
        <%= image_tag(@question.user.image_url, :class => 'list-profile-image') if @question.user.image? %>
    <% end %>
  </div>

  <div class="col-sm-9 col-xs-8">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <%= link_to(@question.user, :class=> 'link-text') do %>
            <%= @question.user.first_name + " " + @question.user.last_name %> <br/>
        <% end %>

        <%= link_to(@question, :class=> 'link-text') do %>
            <%= @question.content %>
        <% end %>
        <br />
        <% @question.labels.each do |label| %>
            <div class="category-label category-<%= @question.category.name.downcase[0..2]%>">
              <%= label.name %>
            </div>
        <% end %>
      </div>
      <div class="col-sm-2 col-cs-12">
        <div class="category-label category-<%= @question.category.name.downcase[0..2]%>">
          <%= @question.category.name %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-2 col-xs-2">
    <%= image_tag 'crystalball.png' %> 
    <span class="metadata-text">
      <%= @question.predictions.count %>
    </span>
  </div>

</div> <!-- End question panel -->
<hr />

<p>
  <% if @question.options.empty? %>
    No options for the question have been defined.
  <% else %>
    <% user_prediction = @question.predictions.find_by_user_id(session[:user_id]) %> <!-- can be nil -->
    <%= form_tag(predictions_path, :method => 'POST') do %>
      <%= hidden_field_tag 'prediction[user_id]', session[:user_id] %>
      <% @question.options.each do |o| %>
      <div class="row">
        <div class="col-sm-6 col-xs-6">
          <% if user_prediction %> <!-- user has made a prediction -->
              <% if user_prediction.option_id == o.id %>
                  <% if o.id == o.question.correct_option_id %>
                      <%= radio_button_tag('prediction[option_id]', o.id, true, :disabled => true, :class => 'correct-prediction')  %>
                  <% else %>
                      <%= radio_button_tag('prediction[option_id]', o.id, true, :disabled => true)  %>
                  <% end %>
              <% else %>
                  <% if o.id == o.question.correct_option_id %>
                      <%= radio_button_tag('prediction[option_id]', o.id, false, :disabled => true, :class => 'wrong-prediction')  %>
                  <% else %>
                      <%= radio_button_tag('prediction[option_id]', o.id, false, :disabled => true)  %>
                  <% end %>
              <% end %>
              <%= label_tag "prediction[option_id_" + o.id.to_s + "]", o.content %>
          <% else %>
              <%= radio_button_tag('prediction[option_id]', o.id)  %>
              <%= label_tag "prediction[option_id_" + o.id.to_s + "]", o.content %>
          <% end %>
        </div>
      </div>
        <% if user_prediction || @question.correct_option %>
        <!-- if the user has made a prediction, display the current predictions -->
        <div class='row'>
          <div class="col-sm-6 col-xs-6" style="padding-left: 50px;">
            <% percentile = o.predictions.count.to_f / o.question.predictions.count.to_f * 100 %>
            <div class="progress">
              <%= o.predictions.count %>
              <div class="progress-bar" role="progressbar" style="width: <%= percentile %>%;">
              </div>
            </div>
          </div>
        </div>
        <% end %> <!-- end of if -->
      <% end %> <!-- end of .each -->
      <% if user_prediction.nil? && ! @question.correct_option %>
      <!-- if user hasn't made a prediction display the prediction button -->
        <%= submit_tag 'Submit', :class => 'btn btn-success' %>
      <% end %>
          <% if question_creator? %>
              <%= link_to 'Edit', edit_question_path(@question), :class => 'btn btn-primary' %>
          <% end %>
<% end %> <!-- end of form -->
  <% end %> <!-- end of else -->
<br />
  <% if question_creator? %>
      <%= link_to 'Add Option', {:controller => 'options', :action => 'new', :question_id => @question.id}, :class => 'btn btn-primary' %>
  <% end %>
<%= link_to 'Back', :back, :class => 'btn btn-default' %>
</div>