config/routes.rb
Psyqic::Application.routes.draw do
  get  'auth/login'
  get  'auth/logout'
  post 'auth/login'
  match 'auth/:provider/callback', to: 'auth#callback'

  resources :predictions
  resources :options
  resources :users
  resources :questions
  resources :categories

  root :to => 'questions#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  attr_accessible :option_id, :user_id
  belongs_to :option
  belongs_to :user
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController

  before_filter :authorize_admin_user, :only => :destroy


  # GET /predictions
  # GET /predictions.json
  def index
    @predictions = Prediction.all
  end

  # POST /predictions
  # POST /predictions.json
  def create
    @prediction = Prediction.new(params[:prediction])
    # @prediction.option_id = params[:option_id]

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to @prediction.option.question, notice: 'Prediction was successfully created.' }
        format.json { render json: @prediction, status: :created, location: @prediction }
      else
        format.html { render action: "new" }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1
  # DELETE /predictions/1.json
  def destroy
    @prediction = Prediction.find(params[:id])
    @prediction.destroy

    respond_to do |format|
      format.html { redirect_to predictions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= form_for(@prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :option_id %><br />
    <%= f.number_field :option_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/predictions/edit.html.erb
<h1>Editing prediction</h1>

<%= render 'form' %>

<%= link_to 'Show', @prediction %> |
<%= link_to 'Back', predictions_path %>

app/views/predictions/index.html.erb
<h1>Listing predictions</h1>

<table>
  <tr>
    <th>Option</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @predictions.each do |prediction| %>
  <tr>
    <td><%= prediction.option_id %></td>
    <td><%= link_to 'Show', prediction %></td>
    <td><%= link_to 'Edit', edit_prediction_path(prediction) %></td>
    <td><%= link_to 'Destroy', prediction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prediction', new_prediction_path %>

app/views/predictions/new.html.erb
<h1>New prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', predictions_path %>

app/views/predictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Option:</b>
  <%= @prediction.option_id %>
</p>


<%= link_to 'Edit', edit_prediction_path(@prediction) %> |
<%= link_to 'Back', predictions_path %>