config/routes.rb
Psyqic::Application.routes.draw do
  get  'auth/login'
  get  'auth/logout'
  post 'auth/login'
  match 'auth/:provider/callback', to: 'auth#callback'

  resources :predictions
  resources :options
  resources :users
  resources :questions
  resources :categories

  root :to => 'questions#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :content, :question_id
  belongs_to :question
  has_many :predictions, :dependent => :destroy
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  before_filter :authorize_question_creator

  def authorize_question_creator
    user = User.find(session[:user_id])
    question = Question.find(params[:question_id])
    if user.id != question.user_id
      flash[:error] = 'The action is only allowed to the creator of the question.'
      redirect_to :back
    end
  end



  # GET /options
  # GET /options.json
  def index
    @options = Option.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new
    @option.question_id = params[:question_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option.question, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<div class="row">
  <div class="col-sm-1 col-xs-2">
    <%= link_to(@option.question.user) do %>
        <%= image_tag(@option.question.user.image_url, :class => 'list-profile-image') if @option.question.user.image? %>
    <% end %>
  </div>

  <div class="col-sm-9 col-xs-10">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <%= link_to(@option.question.user, :class=> 'link-text') do %>
            <%= @option.question.user.first_name + " " + @option.question.user.last_name %> <br/>
        <% end %>

        <%= link_to(@option.question, :class=> 'link-text') do %>
            <%= @option.question.content %>
        <% end %>
      </div>
      <div class="col-sm-2 col-cs-12">
        <div class="category-label category-<%= @option.question.category.name.downcase[0..2]%>">
          <%= @option.question.category.name %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-xs-12">
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :question_id %>

  <br />

  <div class="field">
    <%= f.label :content, 'Option:' %><br />
    <%= f.text_area :content, :rows => 2 %>
  </div>
  </div>
</div>

  <br />

  <div class="actions">
    <%= f.submit 'Save Option', :class=> 'btn btn-primary btn' %>
    <%= link_to 'Cancel', :back, :class => 'btn btn-default btn' %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @options.each do |option| %>
  <tr>
    <td><%= option.question_id %></td>
    <td><%= option.content %></td>
    <td><%= link_to 'Show', option %></td>
    <td><%= link_to 'Edit', edit_option_path(option) %></td>
    <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h3>New Option</h3>
<div class="container">
  <%= render 'form' %>
</div>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @option.question_id %>
</p>

<p>
  <b>Content:</b>
  <%= @option.content %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>